version: '3'

services:

  nginx:
    build:
      context: .
      dockerfile: nginx.docker
    command: nginx -g "daemon off;"
    depends_on:
      - php
    ports:
      - "2586:80"
    networks:
      - cocoa-studio-network

  php:
    build:
      context: .
      dockerfile: php.docker
    volumes:
      - ./:/app
    working_dir: /app/public
    command: php-fpm
    depends_on:
      - db
    ports:
      - "9000:9000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: cocoa_studio_db
      DB_USERNAME: root
      DB_PASSWORD: secret
      CACHE_DRIVER: array
    networks:
      - cocoa-studio-network

  db:
    image: mysql:5.7.22
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: cocoa_studio_db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - cocoa-studio-network

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      depends_on:
        - db
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=db
        - PMA_PORT=3306
        - PMA_USER=root
        - PMA_PASSWORD=secret
      restart: always
      ports:
        - 2021:80
      volumes:
        - /sessions
      networks:
        - cocoa-studio-network

networks:
  cocoa-studio-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
